// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqfmaptctfkjbjybqire.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZm1hcHRjdGZramJqeWJxaXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODc2NzQsImV4cCI6MjA1Nzk2MzY3NH0.tNUr2NtG6tdBncQPmJb_xYk-kFaNVXug_6tjO2tA_YI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);